export enum VehiculeCategorie {
  VEHICULES_LEGERS = 'VEHICULES_LEGERS',
  VEHICULES_UTILITAIRES = 'VEHICULES_UTILITAIRES',
  CAMIONS = 'CAMIONS',
  VEHICULES_ELECTRIQUES_HYBRIDES = 'VEHICULES_ELECTRIQUES_HYBRIDES',
  MOTOS_SCOOTERS = 'MOTOS_SCOOTERS',
  ENGINS_AGRICOLES = 'ENGINS_AGRICOLES',
  VEHICULES_CHANTIER = 'VEHICULES_CHANTIER'
}